<a href="https://colab.research.google.com/github/muneer-ahmad10/End_Module_exam_prep/blob/main/Weak_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Jupyter Notebook Execution Order**

In [5]:
x=100

In [6]:
print(x)

100


# **Broadcasting**

# **Tensor Memory**

In [15]:
import torch

In [16]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [18]:
y=x.view(3,2)

In [19]:
y[0][0]=100

In [22]:
y

tensor([[100,   2],
        [  3,   4],
        [  5,   6]])

In [21]:
x

tensor([[100,   2,   3],
        [  4,   5,   6]])

In [23]:
z=x.transpose(0,1)

In [24]:
z

tensor([[100,   4],
        [  2,   5],
        [  3,   6]])

In [25]:
x

tensor([[100,   2,   3],
        [  4,   5,   6]])

In [27]:
x.view(3,2)

tensor([[100,   2],
        [  3,   4],
        [  5,   6]])

# **PyTorch Autograd + the Training Loop**