<a href="https://colab.research.google.com/github/muneer-ahmad10/End_Module_exam_prep/blob/main/Weak_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Jupyter Notebook Execution Order**

In [5]:
x=100

In [6]:
print(x)

100


# **Broadcasting**

# **Tensor Memory**

In [15]:
import torch

In [16]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [18]:
y=x.view(3,2)

In [19]:
y[0][0]=100

In [22]:
y

tensor([[100,   2],
        [  3,   4],
        [  5,   6]])

In [21]:
x

tensor([[100,   2,   3],
        [  4,   5,   6]])

In [23]:
z=x.transpose(0,1)

In [24]:
z

tensor([[100,   4],
        [  2,   5],
        [  3,   6]])

In [25]:
x

tensor([[100,   2,   3],
        [  4,   5,   6]])

In [27]:
x.view(3,2)

tensor([[100,   2],
        [  3,   4],
        [  5,   6]])

# **PyTorch Autograd + the Training Loop**

In [28]:
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [31]:
y=x**2 + 3*x
y

tensor(10., grad_fn=<AddBackward0>)

In [32]:
y.backward()

In [33]:
y

tensor(10., grad_fn=<AddBackward0>)

In [36]:
print(x.grad)

tensor(7.)


### **training loop in 5 Steps**



*   clear old grads
*   forward pass
*   compute loss
*   Backward pass
*   update weigts



In [ ]:
# for epoch in (num_epochs):
#   optimizer.zero_grad()
#   output=model(input)
#   loss=criterion(output,target)
#   loss.backward()
#   optimizer.step()

# **Questions and Answers**

1-You forget optimizer.zero_grad(). What concretely happens to your gradients over 2 iterations?

gradients accumulate by addition, not "recalculate wrong." After iteration 1, .grad holds the gradient from batch 1. In iteration 2, backward() adds batch 2's gradient on top of that — so .grad now equals batch1_grad + batch2_grad. The optimizer then updates weights using this inflated, incorrect sum instead of just batch 2's true gradient — which is why training becomes unstable or converges to the wrong place.

2-Why is loss.backward() called before optimizer.step(), and not the other way around?

optimizer.step() updates weights using whatever is currently stored in .grad. If you called step() before backward(), .grad would either be empty (None) or hold stale values from the previous iteration — so the optimizer would update weights using the wrong (or no) gradient information for the current batch. The order is mechanical, not about "getting loss minimum" directly — backward() is what computes the gradients that make minimization possible; step() just applies whatever gradient is sitting there at that moment.

3-x = torch.tensor(3.0, requires_grad=True); y = x**3. What is x.grad after y.backward()? (do the calculus)

y = x³ → dy/dx = 3x² → at x=3: 3 × 9 = 27

4-What would happen if you used nn.MSELoss for a classification problem with class labels 0,1,2 instead of nn.CrossEntropyLoss

MSE is for regression (continuous targets), CrossEntropy is for classification (discrete, unordered categories) — using the wrong one doesn't just work worse, it optimizes toward the wrong objective entirely.